version: "3"

services:
  rest_opencv_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest_opencv_api
    volumes:
      - ./:/home
    working_dir: /home
    ports:
      - 8080:80
    tty: true
